kind: Service
apiVersion: v1
metadata:
  name: bdt-feature-selection
  namespace: operational-inteligence
  labels:
    k8s-app: bdt-feature-selection
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: bdt-feature-selection
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bdt-feature-selection
  namespace: operational-inteligence
  labels:
    k8s-app: bdt-feature-selection
  annotations:
    kubernetes.io/ingress.class: nginx    
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - bdtfs.uc.ssl-hep.org
    secretName: bdtfs-cert
  rules:
    - host: bdtfs.uc.ssl-hep.org
      http:
        paths:
        - path: /
          backend:
            servicename: bdt-feature-selection
            servicePort: 80